-- Turmas
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(11,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(12,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(21,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(22,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(31,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(32,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(33,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(41,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(42,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(43,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(51,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(52,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(53,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(61,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(62,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(63,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(71,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(72,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(73,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(81,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(82,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(83,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(91,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(92,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(93,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(101,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(102,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(103,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(201,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(202,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(203,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(301,25,0);
INSERT INTO tb_turma(numero,capacidade,tamanho) VALUES(302,25,0);


-- Alunos

INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(1, 'Gustavo Henrique', 'gustavohenrique@escola.com', 302);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(2, 'Ana Sophia Araújo', 'ana.sophia.araújo2@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(3, 'Sra. Elisa das Neves', 'sra..elisa.das.neves3@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(4, 'Vicente Cavalcanti', 'vicente.cavalcanti4@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(5, 'Sarah Viana', 'sarah.viana5@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(6, 'Nicolas Pereira', 'nicolas.pereira6@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(7, 'Antônio Carvalho', 'antônio.carvalho7@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(8, 'Enzo Santos', 'enzo.santos8@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(9, 'Alice da Paz', 'alice.da.paz9@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(10, 'Dra. Pietra Viana', 'dra..pietra.viana10@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(11, 'Clarice Porto', 'clarice.porto11@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(12, 'Emilly Almeida', 'emilly.almeida12@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(13, 'Samuel Pereira', 'samuel.pereira13@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(14, 'Dr. Davi Lucas da Rosa', 'dr..davi.lucas.da.rosa14@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(15, 'Sr. Bryan Nascimento', 'sr..bryan.nascimento15@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(16, 'João Gabriel Monteiro', 'joao.gabriel.monteiro16@escola.com', 11);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(17, 'Emanuella Barbosa', 'emanuella.barbosa17@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(18, 'Sra. Maria Alice Costa', 'sra..maria.alice.costa18@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(19, 'Ana Júlia Vieira', 'ana.júlia.vieira19@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(20, 'Pedro Lucas Moreira', 'pedro.lucas.moreira20@escola.com', 1);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(21, 'Caroline Campos', 'caroline.campos21@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(22, 'Rafael Dias', 'rafael.dias22@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(23, 'Bruno Dias', 'bruno.dias23@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(24, 'João Miguel Freitas', 'joao.miguel.freitas24@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(25, 'Maysa Moreira', 'maysa.moreira25@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(26, 'João Lucas Moraes', 'joao.lucas.moraes26@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(27, 'Raul Fogaça', 'raul.fogaca27@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(28, 'Dra. Melissa Cardoso', 'dra..melissa.cardoso28@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(29, 'Maysa da Cunha', 'maysa.da.cunha29@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(30, 'Sabrina Farias', 'sabrina.farias30@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(31, 'Lucas Gabriel Nascimento', 'lucas.gabriel.nascimento31@escola.com', 12);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(32, 'Pedro Miguel das Neves', 'pedro.miguel.das.neves32@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(33, 'Giovanna Caldeira', 'giovanna.caldeira33@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(34, 'Arthur Lopes', 'arthur.lopes34@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(35, 'Emanuelly Campos', 'emanuelly.campos35@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(36, 'Miguel Lopes', 'miguel.lopes36@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(37, 'Pietro Sales', 'pietro.sales37@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(38, 'Melissa Ramos', 'melissa.ramos38@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(39, 'Francisco Cunha', 'francisco.cunha39@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(40, 'Vinicius Teixeira', 'vinicius.teixeira40@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(41, 'Vinicius Pereira', 'vinicius.pereira41@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(42, 'Juliana Moreira', 'juliana.moreira42@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(43, 'Daniel Silva', 'daniel.silva43@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(44, 'Ana Laura Barros', 'ana.laura.barros44@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(45, 'Davi Lucas da Cruz', 'davi.lucas.da.cruz45@escola.com',21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(46, 'Lara Campos', 'lara.campos46@escola.com', 21);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(47, 'Isis Rezende', 'isis.rezende47@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(48, 'Eloah Vieira', 'eloah.vieira48@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(49, 'Rodrigo Correia', 'rodrigo.correia49@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(50, 'Maria Alice Fogaça', 'maria.alice.fogaca50@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(51, 'Heloísa Correia', 'heloísa.correia51@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(52, 'Leandro da Cruz', 'leandro.da.cruz52@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(53, 'Agatha Ferreira', 'agatha.ferreira53@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(54, 'Sophie da Luz', 'sophie.da.luz4@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(55, 'Ana Lívia Jesus', 'ana.lívia.jesus55@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(56, 'Lívia da Paz', 'lívia.da.paz56@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(57, 'João Lucas da Cruz', 'joao.lucas.da.cruz57@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(58, 'Stephany Souza', 'stephany.souza58@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(59, 'Noah Martins', 'noah.martins59@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(60, 'Alexia Correia', 'alexia.correia60@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(61, 'Dr. Erick Caldeira', 'dr..erick.caldeira61@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(62, 'Miguel Cardoso', 'miguel.cardoso62@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(63, 'Thomas Rodrigues', 'thomas.rodrigues63@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(64, 'Vitor Hugo Teixeira', 'vitor.hugo.teixeira64@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(622, 'Cauê Ribeiro', 'caue.ribeiro622@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(66, 'Bárbara Ferreira', 'barbara.ferreira66@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(67, 'Maria Pereira', 'maria.pereira67@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(68, 'Marcelo da Paz', 'marcelo.da.paz68@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(69, 'Sra. Juliana Moura', 'sra..juliana.moura69@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(70, 'Manuela Porto', 'manuela.porto70@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(71, 'Felipe das Neves', 'felipe.das.neves71@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(72, 'Joaquim Aragão', 'joaquim.aragao72@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(73, 'Maria Clara Dias', 'maria.clara.dias73@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(74, 'Clarice Almeida', 'clarice.almeida74@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(75, 'Thales Caldeira', 'thales.caldeira75@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(76, 'Bernardo Azevedo', 'bernardo.azevedo76@escola.com', 22);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(77, 'Sr. Luiz Gustavo Duarte', 'sr..luiz.gustavo.duarte77@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(78, 'Raul Rodrigues', 'raul.rodrigues78@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(79, 'Marcelo Costela', 'marcelo.costela79@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(80, 'Dra. Maria Julia Ribeiro', 'dra..maria.julia.ribeiro80@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(81, 'Yuri Ribeiro', 'yuri.ribeiro81@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(82, 'Caroline Castro', 'caroline.castro82@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(83, 'Rafael Pinto', 'rafael.pinto83@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(84, 'Dr. Juan Rezende', 'dr..juan.rezende84@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(85, 'Srta. Nicole Castro', 'srta..nicole.castro85@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(86, 'João Mendes', 'joao.mendes86@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(87, 'Felipe da Mota', 'felipe.da.mota87@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(88, 'Luiz Otávio Porto', 'luiz.otavio.porto88@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(89, 'Kevin da Mata', 'kevin.da.mata89@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(90, 'Lucas Gabriel Farias', 'lucas.gabriel.farias90@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(91, 'Leonardo Vieira', 'leonardo.vieira91@escola.com', 23);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(92, 'Benjamin Viana', 'benjamin.viana92@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(93, 'Bryan Duarte', 'bryan.duarte93@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(94, 'Juan Rodrigues', 'juan.rodrigues94@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(95, 'Clara Nunes', 'clara.nunes95@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(96, 'Davi Luiz Nascimento', 'davi.luiz.nascimento96@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(97, 'João Pedro Ferreira', 'joao.pedro.ferreira97@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(98, 'Esther Pereira', 'esther.pereira98@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(99, 'Dra. Valentina Rodrigues', 'dra..valentina.rodrigues99@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(100, 'Diogo Gonçalves', 'diogo.goncalves100@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(101, 'Benício Viana', 'benício.viana101@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(102, 'Vinicius Lopes', 'vinicius.lopes102@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(103, 'Benjamin Rocha', 'benjamin.rocha103@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(104, 'Marcela da Cruz', 'marcela.da.cruz104@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(105, 'Luiz Gustavo Cardoso', 'luiz.gustavo.cardoso105@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(106, 'Bernardo Campos', 'bernardo.campos106@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(107, 'Eduarda Nunes', 'eduarda.nunes107@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(108, 'Miguel Farias', 'miguel.farias108@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(109, 'Maria Vitória Barbosa', 'maria.vitória.barbosa109@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(110, 'Ana Júlia Peixoto', 'ana.júlia.peixoto110@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(111, 'Maria Luiza Silveira', 'maria.luiza.silveira111@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(112, 'Dr. Emanuel Lopes', 'dr..emanuel.lopes112@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(113, 'Francisco Novaes', 'francisco.novaes113@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(114, 'Raul Jesus', 'raul.jesus114@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(115, 'Gabrielly Cardoso', 'gabrielly.cardoso115@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(116, 'Lorenzo Castro', 'lorenzo.castro116@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(117, 'Luiz Otávio da Rosa', 'luiz.otavio.da.rosa117@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(118, 'Emanuella Costela', 'emanuella.costela118@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(119, 'Sr. Felipe Moura', 'sr..felipe.moura119@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(120, 'Davi Lucca Pires', 'davi.lucca.pires120@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(121, 'Rafaela Jesus', 'rafaela.jesus121@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(122, 'Milena Souza', 'milena.souza122@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(123, 'Raul Vieira', 'raul.vieira123@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(124, 'Rafael Cavalcanti', 'rafael.cavalcanti124@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(125, 'Francisco Correia', 'francisco.correia125@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(126, 'Vinicius Vieira', 'vinicius.vieira126@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(127, 'Gabriel Gomes', 'gabriel.gomes127@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(128, 'Cecília Mendes', 'cecília.mendes128@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(129, 'Rodrigo Ferreira', 'rodrigo.ferreira129@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(130, 'Luiza Fernandes', 'luiza.fernandes130@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(131, 'Bryan Pereira', 'bryan.pereira131@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(132, 'Augusto Almeida', 'augusto.almeida132@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(133, 'Sr. Pedro Miguel Ferreira', 'sr..pedro.miguel.ferreira133@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(134, 'Vicente Pires', 'vicente.pires134@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(135, 'Rafaela Pereira', 'rafaela.pereira135@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(136, 'Alana Correia', 'alana.correia136@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(137, 'Ryan da Costa', 'ryan.da.costa137@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(138, 'Alícia Moura', 'alícia.moura138@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(139, 'Maria Clara da Conceição', 'maria.clara.da.conceicao139@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(140, 'Ana Barbosa', 'ana.barbosa140@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(141, 'João Guilherme Barbosa', 'joao.guilherme.barbosa141@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(142, 'Sr. Rodrigo Farias', 'sr..rodrigo.farias142@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(143, 'Ana Lívia Moraes', 'ana.lívia.moraes143@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(144, 'Júlia da Costa', 'júlia.da.costa144@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(145, 'Davi Lucca da Luz', 'davi.lucca.da.luz145@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(146, 'Alice da Luz', 'alice.da.luz146@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(147, 'Sra. Valentina Oliveira', 'sra..valentina.oliveira147@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(148, 'Sarah Farias', 'sarah.farias148@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(149, 'Davi Lucca Cavalcanti', 'davi.lucca.cavalcanti149@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(150, 'Alícia Ribeiro', 'alícia.ribeiro150@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(151, 'Eduardo Ramos', 'eduardo.ramos151@escola.com', 41);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(152, 'Dr. Enzo das Neves', 'dr..enzo.das.neves152@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(153, 'Rafael da Mota', 'rafael.da.mota153@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(154, 'Helena Freitas', 'helena.freitas154@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(155, 'Vitor Freitas', 'vitor.freitas155@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(156, 'Dr. Renan Teixeira', 'dr..renan.teixeira156@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(157, 'Sr. Carlos Eduardo Ferreira', 'sr..carlos.eduardo.ferreira157@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(158, 'Nathan Ferreira', 'nathan.ferreira158@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(159, 'Calebe Pinto', 'calebe.pinto159@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(160, 'Dr. Leandro Silva', 'dr..leandro.silva160@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(161, 'João Pedro da Mota', 'joao.pedro.da.mota161@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(162, 'Augusto Pinto', 'augusto.pinto162@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(163, 'Luiz Henrique Teixeira', 'luiz.henrique.teixeira163@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(164, 'Rebeca da Paz', 'rebeca.da.paz164@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(165, 'Dr. Bernardo Melo', 'dr..bernardo.melo165@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(166, 'Gabrielly Costa', 'gabrielly.costa166@escola.com', 42);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(167, 'Sra. Lívia Lima', 'sra..lívia.lima167@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(168, 'Júlia Martins', 'júlia.martins168@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(169, 'Pietra Gonçalves', 'pietra.goncalves169@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(170, 'Ana da Mota', 'ana.da.mota170@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(171, 'Natália Nascimento', 'natalia.nascimento171@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(172, 'Sofia da Luz', 'sofia.da.luz172@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(173, 'Maria Fernanda Jesus', 'maria.fernanda.jesus173@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(174, 'Maria Clara Almeida', 'maria.clara.almeida174@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(175, 'Gustavo Henrique da Rocha', 'gustavo.henrique.da.rocha175@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(176, 'Valentina Martins', 'valentina.martins176@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(177, 'Laura Pires', 'laura.pires177@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(178, 'Clara Silva', 'clara.silva178@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(179, 'Vitória da Cunha', 'vitória.da.cunha179@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(180, 'Ana Júlia Gomes', 'ana.júlia.gomes180@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(181, 'Mirella Melo', 'mirella.melo181@escola.com', 43);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(182, 'Vitor Gabriel Duarte', 'vitor.gabriel.duarte182@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(183, 'Gabriela das Neves', 'gabriela.das.neves183@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(184, 'Danilo Araújo', 'danilo.araújo184@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(185, 'Felipe Ribeiro', 'felipe.ribeiro185@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(186, 'Stella Cardoso', 'stella.cardoso186@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(187, 'Kamilly da Mota', 'kamilly.da.mota187@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(188, 'Dra. Joana Sales', 'dra..joana.sales188@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(189, 'Elisa da Conceição', 'elisa.da.conceicao189@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(190, 'Olivia Almeida', 'olivia.almeida190@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(191, 'Yago Pereira', 'yago.pereira191@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(192, 'Davi Silveira', 'davi.silveira192@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(193, 'Ana Beatriz Farias', 'ana.beatriz.farias193@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(194, 'Lorenzo Cunha', 'lorenzo.cunha194@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(195, 'Natália Souza', 'natalia.souza195@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(196, 'Maria Vitória Lopes', 'maria.vitória.lopes196@escola.com', 51);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(197, 'Mariana Santos', 'mariana.santos197@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(198, 'Maria Clara Porto', 'maria.clara.porto198@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(199, 'Vinicius Ribeiro', 'vinicius.ribeiro199@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(200, 'Emanuella Farias', 'emanuella.farias200@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(201, 'Emilly Silveira', 'emilly.silveira201@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(202, 'Marina Duarte', 'marina.duarte202@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(203, 'Leonardo Cardoso', 'leonardo.cardoso203@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(204, 'Sra. Eduarda Fogaça', 'sra..eduarda.fogaca204@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(205, 'Dr. Marcelo Cardoso', 'dr..marcelo.cardoso205@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(206, 'Davi Lucas Dias', 'davi.lucas.dias206@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(207, 'Olivia da Costa', 'olivia.da.costa207@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(208, 'Srta. Ana Clara Peixoto', 'srta..ana.clara.peixoto208@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(209, 'Helena Viana', 'helena.viana209@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(210, 'Kamilly Caldeira', 'kamilly.caldeira210@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(211, 'Kaique Nogueira', 'kaique.nogueira211@escola.com', 52);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(212, 'Pietra Aragão', 'pietra.aragao212@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(213, 'Isis Rocha', 'isis.rocha213@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(214, 'João Gabriel Jesus', 'joao.gabriel.jesus214@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(215, 'Kamilly Teixeira', 'kamilly.teixeira215@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(216, 'Dra. Maria Cecília das Neves', 'dra..maria.cecília.das.neves216@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(217, 'Clarice Fogaça', 'clarice.fogaca217@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(218, 'Luiza Araújo', 'luiza.araújo218@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(219, 'Heloísa Nunes', 'heloísa.nunes219@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(220, 'Srta. Letícia Costela', 'srta..letícia.costela220@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(221, 'Maria Alice Araújo', 'maria.alice.araújo221@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(222, 'Maria Sophia Araújo', 'maria.sophia.araújo222@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(223, 'Pedro Pereira', 'pedro.pereira223@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(224, 'Lucas Gabriel da Mata', 'lucas.gabriel.da.mata224@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(225, 'Francisco Nascimento', 'francisco.nascimento225@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(226, 'Sr. Lorenzo Martins', 'sr..lorenzo.martins226@escola.com', 53);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(227, 'Dr. Guilherme Peixoto', 'dr..guilherme.peixoto227@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(228, 'Bruno Ribeiro', 'bruno.ribeiro228@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(229, 'Vinicius Viana', 'vinicius.viana229@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(230, 'João Felipe das Neves', 'joao.felipe.das.neves230@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(231, 'Ana Clara Barbosa', 'ana.clara.barbosa231@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(232, 'Felipe da Paz', 'felipe.da.paz232@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(233, 'Pedro Henrique da Costa', 'pedro.henrique.da.costa233@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(234, 'Cauê Ribeiro', 'caue.ribeiro234@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(235, 'Ana Sophia da Rosa', 'ana.sophia.da.rosa235@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(236, 'Pietra Fernandes', 'pietra.fernandes236@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(237, 'Sr. Otávio Correia', 'sr..otavio.correia237@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(238, 'Henrique Cavalcanti', 'henrique.cavalcanti238@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(239, 'Alice Lima', 'alice.lima239@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(240, 'Nicole Nascimento', 'nicole.nascimento240@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(241, 'Raquel da Paz', 'raquel.da.paz241@escola.com', 61);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(242, 'Nicolas Farias', 'nicolas.farias242@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(243, 'Samuel Jesus', 'samuel.jesus243@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(244, 'Maria Vitória Costa', 'maria.vitória.costa244@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(245, 'Valentina Barbosa', 'valentina.barbosa245@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(246, 'Dr. Rafael Moura', 'dr..rafael.moura246@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(247, 'Luiz Fernando Mendes', 'luiz.fernando.mendes247@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(248, 'Kaique Rodrigues', 'kaique.rodrigues248@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(249, 'Leandro Moreira', 'leandro.moreira249@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(250, 'Laís da Costa', 'laís.da.costa250@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(251, 'Camila Silveira', 'camila.silveira251@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(252, 'Emanuelly Teixeira', 'emanuelly.teixeira252@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(253, 'Letícia Pinto', 'letícia.pinto253@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(254, 'Dra. Emanuelly Martins', 'dra..emanuelly.martins254@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(255, 'Bryan Freitas', 'bryan.freitas255@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(256, 'Elisa Rezende', 'elisa.rezende256@escola.com', 62);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(257, 'Mariana Nascimento', 'mariana.nascimento257@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(258, 'Sr. Luiz Felipe Martins', 'sr..luiz.felipe.martins258@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(259, 'Luigi da Rosa', 'luigi.da.rosa259@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(260, 'Dr. Joaquim Freitas', 'dr..joaquim.freitas260@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(261, 'Pietra Freitas', 'pietra.freitas261@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(262, 'Alana Silveira', 'alana.silveira262@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(263, 'Bruno Duarte', 'bruno.duarte263@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(264, 'Sra. Luiza Duarte', 'sra..luiza.duarte264@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(265, 'Sra. Melissa Rodrigues', 'sra..melissa.rodrigues265@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(266, 'Vitória Aragão', 'vitória.aragao266@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(267, 'Gustavo das Neves', 'gustavo.das.neves267@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(268, 'Olivia Farias', 'olivia.farias268@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(269, 'Rafael Moura', 'rafael.moura269@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(270, 'Maria Clara Souza', 'maria.clara.souza270@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(271, 'Dr. Vinicius Vieira', 'dr..vinicius.vieira271@escola.com', 63);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(272, 'Dr. Samuel Ramos', 'dr..samuel.ramos272@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(273, 'Henrique Fernandes', 'henrique.fernandes273@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(274, 'Cauã da Mota', 'caua.da.mota274@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(275, 'Sr. Vinicius Teixeira', 'sr..vinicius.teixeira275@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(276, 'Srta. Caroline da Rosa', 'srta..caroline.da.rosa276@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(277, 'Sra. Emilly Souza', 'sra..emilly.souza277@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(278, 'Esther Castro', 'esther.castro278@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(279, 'Gustavo Dias', 'gustavo.dias279@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(280, 'Sr. Heitor Alves', 'sr..heitor.alves280@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(281, 'Dra. Ana Freitas', 'dra..ana.freitas281@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(282, 'Benjamin Vieira', 'benjamin.vieira282@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(283, 'Samuel Costela', 'samuel.costela283@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(284, 'Sophia Rodrigues', 'sophia.rodrigues284@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(285, 'André Gomes', 'andre.gomes285@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(286, 'Luana Pires', 'luana.pires286@escola.com', 71);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(287, 'Sr. Benjamin Fernandes', 'sr..benjamin.fernandes287@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(288, 'Ana Sophia Campos', 'ana.sophia.campos288@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(289, 'Luiza Cardoso', 'luiza.cardoso289@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(290, 'Marina Barros', 'marina.barros290@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(291, 'Davi Lucas Jesus', 'davi.lucas.jesus291@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(292, 'Felipe Costa', 'felipe.costa292@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(293, 'Sophie Peixoto', 'sophie.peixoto293@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(294, 'Maria Vitória das Neves', 'maria.vitória.das.neves294@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(295, 'Isis Porto', 'isis.porto295@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(296, 'Fernanda Pereira', 'fernanda.pereira296@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(297, 'Miguel Caldeira', 'miguel.caldeira297@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(298, 'Sarah Castro', 'sarah.castro298@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(299, 'Pedro Lucas da Rosa', 'pedro.lucas.da.rosa299@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(300, 'Rafael Cardoso', 'rafael.cardoso300@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(301, 'Erick da Luz', 'erick.da.luz301@escola.com', 72);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(302, 'Ana Julia da Cruz', 'ana.julia.da.cruz302@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(303, 'Juan Porto', 'juan.porto303@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(304, 'Dra. Lorena Gonçalves', 'dra..lorena.goncalves304@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(305, 'Enzo Gomes', 'enzo.gomes305@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(306, 'Sra. Pietra Ramos', 'sra..pietra.ramos306@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(307, 'Rodrigo Dias', 'rodrigo.dias307@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(308, 'Yuri da Paz', 'yuri.da.paz308@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(309, 'Ana Sophia Viana', 'ana.sophia.viana309@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(310, 'Pedro da Costa', 'pedro.da.costa310@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(311, 'Danilo Cardoso', 'danilo.cardoso311@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(312, 'Davi Luiz Lima', 'davi.luiz.lima312@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(313, 'Sofia Gomes', 'sofia.gomes313@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(314, 'Ana Vitória Rezende', 'ana.vitória.rezende314@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(315, 'Sra. Pietra Nunes', 'sra..pietra.nunes315@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(316, 'Luiz Fernando Viana', 'luiz.fernando.viana316@escola.com', 73);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(317, 'Laura Cardoso', 'laura.cardoso317@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(318, 'Amanda Pinto', 'amanda.pinto318@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(319, 'Sra. Maria Fernandes', 'sra..maria.fernandes319@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(320, 'Bryan Dias', 'bryan.dias320@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(321, 'Maria Julia Aragão', 'maria.julia.aragao321@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(322, 'Emanuelly Barbosa', 'emanuelly.barbosa322@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(323, 'Lucas Silveira', 'lucas.silveira323@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(324, 'Laura Freitas', 'laura.freitas324@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(325, 'Nathan Pinto', 'nathan.pinto325@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(326, 'Luiza Carvalho', 'luiza.carvalho326@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(327, 'Isabel Oliveira', 'isabel.oliveira327@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(328, 'Dr. Raul Cavalcanti', 'dr..raul.cavalcanti328@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(329, 'Isaac Oliveira', 'isaac.oliveira329@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(330, 'Sra. Esther Nunes', 'sra..esther.nunes330@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(331, 'Alícia Ramos', 'alícia.ramos331@escola.com', 81);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(332, 'Ian Fernandes', 'ian.fernandes332@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(333, 'Sr. Vitor Nunes', 'sr..vitor.nunes333@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(334, 'Agatha Viana', 'agatha.viana334@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(335, 'Júlia Barros', 'júlia.barros335@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(336, 'Luiz Henrique Moreira', 'luiz.henrique.moreira336@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(337, 'Sophia Sales', 'sophia.sales337@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(338, 'Laura Barros', 'laura.barros338@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(339, 'Gabriel Vieira', 'gabriel.vieira339@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(340, 'Gustavo Henrique Pires', 'gustavo.henrique.pires340@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(341, 'Sra. Ana Vitória Araújo', 'sra..ana.vitória.araújo341@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(342, 'Maria Duarte', 'maria.duarte342@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(343, 'Srta. Gabriela Vieira', 'srta..gabriela.vieira343@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(344, 'Marcos Vinicius Oliveira', 'marcos.vinicius.oliveira344@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(345, 'Enzo Gabriel Correia', 'enzo.gabriel.correia345@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(346, 'Ana Vitória da Costa', 'ana.vitória.da.costa346@escola.com', 82);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(347, 'Raquel Gonçalves', 'raquel.goncalves347@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(348, 'Rafaela Fogaça', 'rafaela.fogaca348@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(349, 'Luana Ribeiro', 'luana.ribeiro349@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(350, 'Lorenzo Vieira', 'lorenzo.vieira350@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(351, 'João Pedro da Mota', 'joao.pedro.da.mota351@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(352, 'Maitê Cunha', 'maite.cunha352@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(353, 'Guilherme Peixoto', 'guilherme.peixoto353@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(354, 'Dr. Alexandre Gomes', 'dr..alexandre.gomes354@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(355, 'Sra. Maria Sophia Rodrigues', 'sra..maria.sophia.rodrigues355@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(356, 'Levi Teixeira', 'levi.teixeira356@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(357, 'Isabel Melo', 'isabel.melo357@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(358, 'Sophie Viana', 'sophie.viana358@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(359, 'Laís Martins', 'laís.martins359@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(360, 'Samuel Duarte', 'samuel.duarte360@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(361, 'Joana Dias', 'joana.dias361@escola.com', 83);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(362, 'Amanda Lopes', 'amanda.lopes362@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(363, 'Sra. Rafaela Nascimento', 'sra..rafaela.nascimento363@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(364, 'Mirella da Costa', 'mirella.da.costa364@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(365, 'Alícia Costela', 'alícia.costela365@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(366, 'Maria Sophia Melo', 'maria.sophia.melo366@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(367, 'Leonardo Castro', 'leonardo.castro367@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(368, 'Laís Alves', 'laís.alves368@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(369, 'Srta. Júlia da Costa', 'srta..júlia.da.costa369@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(370, 'Lucas Ferreira', 'lucas.ferreira370@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(371, 'Dr. Pietro Cardoso', 'dr..pietro.cardoso371@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(372, 'Dr. Ian Rodrigues', 'dr..ian.rodrigues372@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(373, 'Alícia Campos', 'alícia.campos373@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(374, 'Pedro Lucas Gomes', 'pedro.lucas.gomes374@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(375, 'Vinicius Carvalho', 'vinicius.carvalho375@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(376, 'Ana Luiza Castro', 'ana.luiza.castro376@escola.com', 91);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(377, 'Bárbara Jesus', 'barbara.jesus377@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(378, 'Augusto Martins', 'augusto.martins378@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(379, 'Gustavo Moraes', 'gustavo.moraes379@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(380, 'Dr. Danilo Farias', 'dr..danilo.farias380@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(381, 'Júlia da Mata', 'júlia.da.mata381@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(382, 'Davi Cardoso', 'davi.cardoso382@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(383, 'Isis Duarte', 'isis.duarte383@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(384, 'Maria Luiza da Conceição', 'maria.luiza.da.conceicao384@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(385, 'Lucas Gabriel Fernandes', 'lucas.gabriel.fernandes385@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(386, 'Eloah Alves', 'eloah.alves386@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(387, 'Esther Viana', 'esther.viana387@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(388, 'Breno Pires', 'breno.pires388@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(389, 'Dr. Pedro Miguel Pereira', 'dr..pedro.miguel.pereira389@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(390, 'Sra. Laís Jesus', 'sra..laís.jesus390@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(391, 'João Pedro Rocha', 'joao.pedro.rocha391@escola.com', 92);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(392, 'Erick Nascimento', 'erick.nascimento392@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(393, 'Isabella Gonçalves', 'isabella.goncalves393@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(394, 'Sra. Alexia Novaes', 'sra..alexia.novaes394@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(395, 'André Barros', 'andre.barros395@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(396, 'Sofia Sales', 'sofia.sales396@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(397, 'Yago Dias', 'yago.dias397@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(398, 'Yasmin Moraes', 'yasmin.moraes398@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(399, 'Pedro Miguel da Mota', 'pedro.miguel.da.mota399@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(400, 'Eloah Cunha', 'eloah.cunha400@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(401, 'Ana Luiza Barbosa', 'ana.luiza.barbosa401@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(402, 'Yuri Pires', 'yuri.pires402@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(403, 'Nathan Moreira', 'nathan.moreira403@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(404, 'Srta. Ana Laura Gonçalves', 'srta..ana.laura.goncalves404@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(405, 'Dr. Davi da Paz', 'dr..davi.da.paz405@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(406, 'Yuri Viana', 'yuri.viana406@escola.com', 27);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(407, 'Dr. Davi Luiz Fernandes', 'dr..davi.luiz.fernandes407@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(408, 'Evelyn Mendes', 'evelyn.mendes408@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(409, 'Lucas Gabriel Cardoso', 'lucas.gabriel.cardoso409@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(410, 'Vitor Gabriel das Neves', 'vitor.gabriel.das.neves410@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(411, 'Rebeca Novaes', 'rebeca.novaes411@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(412, 'Isabelly Carvalho', 'isabelly.carvalho412@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(413, 'Alana Ferreira', 'alana.ferreira413@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(414, 'Ana Vitória Ramos', 'ana.vitória.ramos414@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(415, 'Dr. Nathan Nascimento', 'dr..nathan.nascimento415@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(416, 'Isadora Cavalcanti', 'isadora.cavalcanti416@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(417, 'Daniela Ribeiro', 'daniela.ribeiro417@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(418, 'Pedro Henrique Martins', 'pedro.henrique.martins418@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(419, 'Clarice Campos', 'clarice.campos419@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(420, 'Letícia Jesus', 'letícia.jesus420@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(421, 'Júlia Correia', 'júlia.correia421@escola.com', 28);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(422, 'Augusto Azevedo', 'augusto.azevedo422@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(423, 'Luiz Felipe Correia', 'luiz.felipe.correia423@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(424, 'Erick Teixeira', 'erick.teixeira424@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(425, 'João Pedro Ramos', 'joao.pedro.ramos425@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(426, 'Dr. Nicolas da Costa', 'dr..nicolas.da.costa426@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(427, 'Milena Castro', 'milena.castro427@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(428, 'Mariana Oliveira', 'mariana.oliveira428@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(429, 'Arthur Moura', 'arthur.moura429@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(430, 'Leonardo Pires', 'leonardo.pires430@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(431, 'João Guilherme Castro', 'joao.guilherme.castro431@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(432, 'Isadora Viana', 'isadora.viana432@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(433, 'Isabella Caldeira', 'isabella.caldeira433@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(434, 'Emilly da Mota', 'emilly.da.mota434@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(435, 'Lorenzo Carvalho', 'lorenzo.carvalho435@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(436, 'Clara Aragão', 'clara.aragao436@escola.com', 29);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(437, 'Yuri Melo', 'yuri.melo437@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(438, 'Cauê da Rocha', 'caue.da.rocha438@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(439, 'Vitor Hugo Vieira', 'vitor.hugo.vieira439@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(440, 'Nicolas da Rosa', 'nicolas.da.rosa440@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(441, 'Isaac da Conceição', 'isaac.da.conceicao441@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(442, 'Agatha Freitas', 'agatha.freitas442@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(443, 'Cauê Viana', 'caue.viana443@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(444, 'Davi Correia', 'davi.correia444@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(445, 'Alice Costela', 'alice.costela445@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(446, 'João Gabriel Duarte', 'joao.gabriel.duarte446@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(447, 'Giovanna Aragão', 'giovanna.aragao447@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(448, 'Francisco Barros', 'francisco.barros448@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(449, 'Vicente Peixoto', 'vicente.peixoto449@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(450, 'Ana Sophia Campos', 'ana.sophia.campos450@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(451, 'Lavínia Moreira', 'lavínia.moreira451@escola.com', 30);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(452, 'Maria Sophia Cavalcanti', 'maria.sophia.cavalcanti452@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(453, 'Lívia das Neves', 'lívia.das.neves453@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(454, 'Amanda Silveira', 'amanda.silveira454@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(455, 'Lorenzo Araújo', 'lorenzo.araújo455@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(456, 'Lucca Nunes', 'lucca.nunes456@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(457, 'Nina Cavalcanti', 'nina.cavalcanti457@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(458, 'Raquel Pires', 'raquel.pires458@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(459, 'Bruno Martins', 'bruno.martins459@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(460, 'Bianca Campos', 'bianca.campos460@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(461, 'Guilherme Vieira', 'guilherme.vieira461@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(462, 'Sra. Isis Souza', 'sra..isis.souza462@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(463, 'Lorenzo Santos', 'lorenzo.santos463@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(464, 'Larissa Castro', 'larissa.castro464@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(465, 'Srta. Milena Vieira', 'srta..milena.vieira465@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(466, 'Srta. Larissa Porto', 'srta..larissa.porto466@escola.com', 31);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(467, 'Juan Mendes', 'juan.mendes467@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(468, 'Juliana Peixoto', 'juliana.peixoto468@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(469, 'Srta. Gabrielly Pereira', 'srta..gabrielly.pereira469@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(470, 'Dr. João Lucas da Costa', 'dr..joao.lucas.da.costa470@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(471, 'Lorena Campos', 'lorena.campos471@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(472, 'Bruno Carvalho', 'bruno.carvalho472@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(473, 'Ana Luiza Moura', 'ana.luiza.moura473@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(474, 'Matheus Caldeira', 'matheus.caldeira474@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(475, 'Maria Eduarda Melo', 'maria.eduarda.melo475@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(476, 'Ana Vitória Oliveira', 'ana.vitória.oliveira476@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(477, 'Dr. Thiago Barros', 'dr..thiago.barros477@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(478, 'Noah Lima', 'noah.lima478@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(479, 'Sr. Murilo Santos', 'sr..murilo.santos479@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(480, 'Davi Lucas Rocha', 'davi.lucas.rocha480@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(481, 'Calebe Monteiro', 'calebe.monteiro481@escola.com', 32);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(482, 'Isadora Correia', 'isadora.correia482@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(483, 'Murilo das Neves', 'murilo.das.neves483@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(484, 'Maria Eduarda Araújo', 'maria.eduarda.araújo484@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(485, 'Mirella Fogaça', 'mirella.fogaca485@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(486, 'Diego Fogaça', 'diego.fogaca486@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(487, 'Sra. Heloísa Monteiro', 'sra..heloísa.monteiro487@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(488, 'Diego da Conceição', 'diego.da.conceicao488@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(489, 'Mirella Nunes', 'mirella.nunes489@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(490, 'Danilo Araújo', 'danilo.araújo490@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(491, 'Vinicius Souza', 'vinicius.souza491@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(492, 'João Miguel Peixoto', 'joao.miguel.peixoto492@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(493, 'Heloísa da Cruz', 'heloísa.da.cruz493@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(494, 'Dr. Thiago Martins', 'dr..thiago.martins494@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(495, 'Maria Vitória Cardoso', 'maria.vitória.cardoso495@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(496, 'Davi Lucas da Cruz', 'davi.lucas.da.cruz496@escola.com', 33);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(497, 'Ana Beatriz Cardoso', 'ana.beatriz.cardoso497@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(498, 'Leonardo Pereira', 'leonardo.pereira498@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(499, 'Maria Pires', 'maria.pires499@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(500, 'Emanuelly da Rosa', 'emanuelly.da.rosa500@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(501, 'Ana Sophia Monteiro', 'ana.sophia.monteiro501@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(502, 'Ana Sophia Gomes', 'ana.sophia.gomes502@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(503, 'Nicole Rodrigues', 'nicole.rodrigues503@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(504, 'Natália Lima', 'natalia.lima504@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(505, 'Enzo Gabriel Novaes', 'enzo.gabriel.novaes505@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(506, 'Ana Carolina Almeida', 'ana.carolina.almeida506@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(507, 'Heitor da Rosa', 'heitor.da.rosa507@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(508, 'Vitor Hugo Fernandes', 'vitor.hugo.fernandes508@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(509, 'Igor Costa', 'igor.costa509@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(510, 'Luiz Felipe Pinto', 'luiz.felipe.pinto510@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(511, 'Cauê Nascimento', 'caue.nascimento511@escola.com', 34);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(512, 'Rafaela Dias', 'rafaela.dias512@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(513, 'Maria Eduarda Moraes', 'maria.eduarda.moraes513@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(514, 'João Vitor Barbosa', 'joao.vitor.barbosa514@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(515, 'Alexia Ramos', 'alexia.ramos515@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(516, 'Ian Pereira', 'ian.pereira516@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(517, 'Juliana Peixoto', 'juliana.peixoto517@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(518, 'Carlos Eduardo Nunes', 'carlos.eduardo.nunes518@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(519, 'Igor da Cunha', 'igor.da.cunha519@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(520, 'Laís Moreira', 'laís.moreira520@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(521, 'Leandro Cavalcanti', 'leandro.cavalcanti521@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(522, 'Leandro Nunes', 'leandro.nunes522@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(523, 'Ana Júlia Novaes', 'ana.júlia.novaes523@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(524, 'Vinicius Mendes', 'vinicius.mendes524@escola.com', 35);
INSERT INTO tb_aluno(id,nome,email,numero_turma) VALUES(525, 'Isaac da Cunha', 'isaac.da.cunha525@escola.com', 35);





